import type { Employee, ModuleNode, Ownership, ShiptOrgState } from "./types";

// ============================================
// EMPLOYEES (108 people total)
// ============================================

const employees: Employee[] = [
  // ===== VP LEVEL (1) =====
  {
    id: "emp-001",
    name: "You (VP Engineering)",
    title: "VP",
    location: "US",
    workstreams: ["Platform"],
    moduleOwnershipIds: [],
    primarySkill: "Architecture",
    secondarySkills: [],
    tenure: 60,
    email: "vp@shipt.com",
  },

  // ===== SENIOR PRINCIPAL ENGINEERS (2 - Report to VP) =====
  {
    id: "emp-002",
    name: "Sarah Chen",
    title: "Senior Principal Engineer",
    location: "US",
    managerId: "emp-001",
    workstreams: ["Platform"],
    moduleOwnershipIds: [],
    primarySkill: "Architecture",
    secondarySkills: ["Backend", "AI/ML"],
    tenure: 72,
    email: "s.chen@shipt.com",
  },
  {
    id: "emp-003",
    name: "Michael Rodriguez",
    title: "Senior Principal Engineer",
    location: "US",
    managerId: "emp-001",
    workstreams: ["Platform"],
    moduleOwnershipIds: [],
    primarySkill: "Architecture",
    secondarySkills: ["Fullstack", "DevOps/SRE"],
    tenure: 84,
    email: "m.rodriguez@shipt.com",
  },

  // ===== DIRECTORS (4 - Each owns a module) =====
  {
    id: "emp-004",
    name: "Jennifer Kim",
    title: "Director",
    location: "US",
    managerId: "emp-001",
    workstreams: ["Search", "Browse", "SEO"],
    moduleOwnershipIds: ["mod-001"],
    primarySkill: "Backend - Search",
    secondarySkills: ["Backend"],
    tenure: 48,
    email: "j.kim@shipt.com",
  },
  {
    id: "emp-005",
    name: "David Thompson",
    title: "Director",
    location: "US",
    managerId: "emp-001",
    workstreams: ["Personalization"],
    moduleOwnershipIds: ["mod-002"],
    primarySkill: "Frontend - Web",
    secondarySkills: ["Fullstack"],
    tenure: 54,
    email: "d.thompson@shipt.com",
  },
  {
    id: "emp-006",
    name: "Maria Garcia",
    title: "Director",
    location: "US",
    managerId: "emp-001",
    workstreams: ["Checkout", "Fulfillment"],
    moduleOwnershipIds: ["mod-003"],
    primarySkill: "Backend",
    secondarySkills: ["Fullstack"],
    tenure: 60,
    email: "m.garcia@shipt.com",
  },
  {
    id: "emp-007",
    name: "Dr. James Chen",
    title: "Director",
    location: "US",
    managerId: "emp-001",
    workstreams: ["Personalization"],
    moduleOwnershipIds: ["mod-004"],
    primarySkill: "AI/ML",
    secondarySkills: ["Backend"],
    tenure: 42,
    email: "j.chen@shipt.com",
  },

  // ===== TRAFFIC, DISCOVERY & GROWTH MODULE (Director: Jennifer Kim) =====
  // --- Senior Engineering Managers (2) ---
  {
    id: "emp-008",
    name: "Robert Wilson",
    title: "Senior Engineering Manager",
    location: "US",
    managerId: "emp-004",
    workstreams: ["Search"],
    moduleOwnershipIds: ["mod-sub-001"],
    primarySkill: "Backend - Search",
    secondarySkills: [],
    tenure: 36,
  },
  {
    id: "emp-009",
    name: "Lisa Anderson",
    title: "Senior Engineering Manager",
    location: "US",
    managerId: "emp-004",
    workstreams: ["Browse"],
    moduleOwnershipIds: ["mod-sub-002"],
    primarySkill: "Fullstack",
    secondarySkills: [],
    tenure: 30,
  },

  // --- Engineering Managers (3) ---
  {
    id: "emp-010",
    name: "Kevin Patel",
    title: "Engineering Manager",
    location: "US",
    managerId: "emp-008",
    workstreams: ["Search"],
    moduleOwnershipIds: [],
    primarySkill: "Backend - Search",
    secondarySkills: [],
    tenure: 24,
  },
  {
    id: "emp-011",
    name: "Amanda Brown",
    title: "Engineering Manager",
    location: "US",
    managerId: "emp-009",
    workstreams: ["Browse"],
    moduleOwnershipIds: ["mod-sub-003"],
    primarySkill: "Frontend - Web",
    secondarySkills: [],
    tenure: 28,
  },
  {
    id: "emp-012",
    name: "Christopher Lee",
    title: "Engineering Manager",
    location: "Nearshore",
    managerId: "emp-009",
    workstreams: ["SEO"],
    moduleOwnershipIds: ["mod-sub-004"],
    primarySkill: "Backend",
    secondarySkills: [],
    tenure: 20,
  },

  // --- Principal Engineers (2) ---
  {
    id: "emp-013",
    name: "Emily Martinez",
    title: "Principal Engineer",
    location: "US",
    managerId: "emp-004",
    workstreams: ["Search"],
    moduleOwnershipIds: [],
    primarySkill: "Backend - Search",
    secondarySkills: ["Architecture"],
    skillLevel: "Principal",
    tenure: 48,
  },
  {
    id: "emp-014",
    name: "Thomas Wang",
    title: "Principal Engineer",
    location: "US",
    managerId: "emp-004",
    workstreams: ["Browse"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - Web",
    secondarySkills: ["Architecture"],
    skillLevel: "Principal",
    tenure: 42,
  },

  // --- Staff Engineers (4) ---
  {
    id: "emp-015",
    name: "Jessica Taylor",
    title: "Staff Engineer",
    location: "US",
    managerId: "emp-010",
    workstreams: ["Search"],
    moduleOwnershipIds: [],
    primarySkill: "Backend - Search",
    secondarySkills: [],
    skillLevel: "Staff",
    tenure: 34,
  },
  {
    id: "emp-016",
    name: "Daniel Kim",
    title: "Staff Engineer",
    location: "US",
    managerId: "emp-011",
    workstreams: ["Browse"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - Web",
    secondarySkills: [],
    skillLevel: "Staff",
    tenure: 30,
  },
  {
    id: "emp-017",
    name: "Rachel Green",
    title: "Staff Engineer",
    location: "US",
    managerId: "emp-012",
    workstreams: ["SEO"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Staff",
    tenure: 28,
  },
  {
    id: "emp-018",
    name: "William Davis",
    title: "Staff Engineer",
    location: "Nearshore",
    managerId: "emp-010",
    workstreams: ["Search"],
    moduleOwnershipIds: [],
    primarySkill: "Fullstack",
    secondarySkills: [],
    skillLevel: "Staff",
    tenure: 26,
  },

  // --- Senior Engineers (6) ---
  {
    id: "emp-019",
    name: "Olivia Johnson",
    title: "Senior Engineer",
    location: "US",
    managerId: "emp-010",
    workstreams: ["Search"],
    moduleOwnershipIds: [],
    primarySkill: "Backend - Search",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 22,
  },
  {
    id: "emp-020",
    name: "James Miller",
    title: "Senior Engineer",
    location: "Nearshore",
    managerId: "emp-010",
    workstreams: ["Search"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 20,
  },
  {
    id: "emp-021",
    name: "Sophia Williams",
    title: "Senior Engineer",
    location: "US",
    managerId: "emp-011",
    workstreams: ["Browse"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - Web",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 24,
  },
  {
    id: "emp-022",
    name: "Benjamin Jones",
    title: "Senior Engineer",
    location: "Nearshore",
    managerId: "emp-011",
    workstreams: ["Browse"],
    moduleOwnershipIds: [],
    primarySkill: "Fullstack",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 18,
  },
  {
    id: "emp-023",
    name: "Emma Garcia",
    title: "Senior Engineer",
    location: "US",
    managerId: "emp-012",
    workstreams: ["SEO"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 21,
  },
  {
    id: "emp-024",
    name: "Alexander Brown",
    title: "Senior Engineer",
    location: "Offshore",
    managerId: "emp-012",
    workstreams: ["SEO"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 16,
  },

  // --- Engineers (7) ---
  {
    id: "emp-025",
    name: "Mia Anderson",
    title: "Engineer",
    location: "Nearshore",
    managerId: "emp-010",
    workstreams: ["Search"],
    moduleOwnershipIds: [],
    primarySkill: "Backend - Search",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 14,
  },
  {
    id: "emp-026",
    name: "Ethan Thomas",
    title: "Engineer",
    location: "Offshore",
    managerId: "emp-010",
    workstreams: ["Search"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 12,
  },
  {
    id: "emp-027",
    name: "Isabella Martinez",
    title: "Engineer",
    location: "US",
    managerId: "emp-011",
    workstreams: ["Browse"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - Web",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 15,
  },
  {
    id: "emp-028",
    name: "Lucas Robinson",
    title: "Engineer",
    location: "Nearshore",
    managerId: "emp-011",
    workstreams: ["Browse"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - Web",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 11,
  },
  {
    id: "emp-029",
    name: "Charlotte Walker",
    title: "Engineer",
    location: "Offshore",
    managerId: "emp-011",
    workstreams: ["Browse"],
    moduleOwnershipIds: [],
    primarySkill: "Fullstack",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 13,
  },
  {
    id: "emp-030",
    name: "Mason Hall",
    title: "Engineer",
    location: "US",
    managerId: "emp-012",
    workstreams: ["SEO"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 10,
  },
  {
    id: "emp-031",
    name: "Ava Allen",
    title: "Engineer",
    location: "Nearshore",
    managerId: "emp-012",
    workstreams: ["SEO"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 9,
  },

  // --- Associate Engineers (2) ---
  {
    id: "emp-032",
    name: "Noah Young",
    title: "Associate Engineer",
    location: "Offshore",
    managerId: "emp-010",
    workstreams: ["Search"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Junior",
    tenure: 6,
  },
  {
    id: "emp-033",
    name: "Harper King",
    title: "Associate Engineer",
    location: "Offshore",
    managerId: "emp-011",
    workstreams: ["Browse"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - Web",
    secondarySkills: [],
    skillLevel: "Junior",
    tenure: 5,
  },

  // ===== CONSIDERATION MODULE (Director: David Thompson) =====
  // --- Senior Engineering Managers (2) ---
  {
    id: "emp-034",
    name: "Patricia Scott",
    title: "Senior Engineering Manager",
    location: "US",
    managerId: "emp-005",
    workstreams: ["Personalization"],
    moduleOwnershipIds: ["mod-sub-005"],
    primarySkill: "Frontend - Web",
    secondarySkills: [],
    tenure: 32,
  },
  {
    id: "emp-035",
    name: "Richard Green",
    title: "Senior Engineering Manager",
    location: "US",
    managerId: "emp-005",
    workstreams: ["Personalization"],
    moduleOwnershipIds: ["mod-sub-006"],
    primarySkill: "Fullstack",
    secondarySkills: [],
    tenure: 34,
  },

  // --- Engineering Managers (3) ---
  {
    id: "emp-036",
    name: "Linda Adams",
    title: "Engineering Manager",
    location: "US",
    managerId: "emp-034",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - App",
    secondarySkills: [],
    tenure: 22,
  },
  {
    id: "emp-037",
    name: "Mark Baker",
    title: "Engineering Manager",
    location: "Nearshore",
    managerId: "emp-034",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - Web",
    secondarySkills: [],
    tenure: 20,
  },
  {
    id: "emp-038",
    name: "Sandra Nelson",
    title: "Engineering Manager",
    location: "US",
    managerId: "emp-035",
    workstreams: ["Personalization"],
    moduleOwnershipIds: ["mod-sub-007"],
    primarySkill: "Fullstack",
    secondarySkills: [],
    tenure: 25,
  },

  // --- Principal Engineers (2) ---
  {
    id: "emp-039",
    name: "Steven Carter",
    title: "Principal Engineer",
    location: "US",
    managerId: "emp-005",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - All",
    secondarySkills: ["Architecture"],
    skillLevel: "Principal",
    tenure: 44,
  },
  {
    id: "emp-040",
    name: "Karen Mitchell",
    title: "Principal Engineer",
    location: "US",
    managerId: "emp-005",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Fullstack",
    secondarySkills: ["Architecture"],
    skillLevel: "Principal",
    tenure: 40,
  },

  // --- Staff Engineers (3) ---
  {
    id: "emp-041",
    name: "Paul Perez",
    title: "Staff Engineer",
    location: "US",
    managerId: "emp-036",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - App",
    secondarySkills: [],
    skillLevel: "Staff",
    tenure: 28,
  },
  {
    id: "emp-042",
    name: "Helen Roberts",
    title: "Staff Engineer",
    location: "US",
    managerId: "emp-037",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - Web",
    secondarySkills: [],
    skillLevel: "Staff",
    tenure: 26,
  },
  {
    id: "emp-043",
    name: "George Turner",
    title: "Staff Engineer",
    location: "Nearshore",
    managerId: "emp-038",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Fullstack",
    secondarySkills: [],
    skillLevel: "Staff",
    tenure: 24,
  },

  // --- Senior Engineers (5) ---
  {
    id: "emp-044",
    name: "Nancy Phillips",
    title: "Senior Engineer",
    location: "US",
    managerId: "emp-036",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - App",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 20,
  },
  {
    id: "emp-045",
    name: "Kenneth Campbell",
    title: "Senior Engineer",
    location: "Nearshore",
    managerId: "emp-036",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - App",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 18,
  },
  {
    id: "emp-046",
    name: "Donna Parker",
    title: "Senior Engineer",
    location: "US",
    managerId: "emp-037",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - Web",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 22,
  },
  {
    id: "emp-047",
    name: "Brian Evans",
    title: "Senior Engineer",
    location: "Nearshore",
    managerId: "emp-038",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Fullstack",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 19,
  },
  {
    id: "emp-048",
    name: "Carol Edwards",
    title: "Senior Engineer",
    location: "Offshore",
    managerId: "emp-038",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - Web",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 17,
  },

  // --- Engineers (6) ---
  {
    id: "emp-049",
    name: "Ronald Collins",
    title: "Engineer",
    location: "Nearshore",
    managerId: "emp-036",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - App",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 14,
  },
  {
    id: "emp-050",
    name: "Ruth Stewart",
    title: "Engineer",
    location: "Offshore",
    managerId: "emp-036",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - App",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 12,
  },
  {
    id: "emp-051",
    name: "Gary Sanchez",
    title: "Engineer",
    location: "US",
    managerId: "emp-037",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - Web",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 13,
  },
  {
    id: "emp-052",
    name: "Michelle Morris",
    title: "Engineer",
    location: "Nearshore",
    managerId: "emp-037",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - Web",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 11,
  },
  {
    id: "emp-053",
    name: "Larry Rogers",
    title: "Engineer",
    location: "Offshore",
    managerId: "emp-038",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Fullstack",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 10,
  },
  {
    id: "emp-054",
    name: "Betty Reed",
    title: "Engineer",
    location: "US",
    managerId: "emp-038",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - All",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 9,
  },

  // --- Associate Engineers (3) ---
  {
    id: "emp-055",
    name: "Jason Cook",
    title: "Associate Engineer",
    location: "Offshore",
    managerId: "emp-036",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - App",
    secondarySkills: [],
    skillLevel: "Junior",
    tenure: 6,
  },
  {
    id: "emp-056",
    name: "Deborah Bell",
    title: "Associate Engineer",
    location: "Offshore",
    managerId: "emp-037",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - Web",
    secondarySkills: [],
    skillLevel: "Junior",
    tenure: 5,
  },
  {
    id: "emp-057",
    name: "Frank Murphy",
    title: "Associate Engineer",
    location: "Nearshore",
    managerId: "emp-038",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Fullstack",
    secondarySkills: [],
    skillLevel: "Junior",
    tenure: 4,
  },

  // ===== PURCHASE AND POST-PURCHASE MODULE (Director: Maria Garcia) =====
  // --- Senior Engineering Managers (3) ---
  {
    id: "emp-058",
    name: "Gregory Bailey",
    title: "Senior Engineering Manager",
    location: "US",
    managerId: "emp-006",
    workstreams: ["Checkout"],
    moduleOwnershipIds: ["mod-sub-008"],
    primarySkill: "Backend",
    secondarySkills: [],
    tenure: 36,
  },
  {
    id: "emp-059",
    name: "Judith Rivera",
    title: "Senior Engineering Manager",
    location: "US",
    managerId: "emp-006",
    workstreams: ["Fulfillment"],
    moduleOwnershipIds: ["mod-sub-010"],
    primarySkill: "Fullstack",
    secondarySkills: [],
    tenure: 33,
  },
  {
    id: "emp-060",
    name: "Raymond Cooper",
    title: "Senior Engineering Manager",
    location: "US",
    managerId: "emp-006",
    workstreams: ["Checkout"],
    moduleOwnershipIds: ["mod-sub-009"],
    primarySkill: "Backend",
    secondarySkills: [],
    tenure: 30,
  },

  // --- Engineering Managers (4) ---
  {
    id: "emp-061",
    name: "Kathleen Richardson",
    title: "Engineering Manager",
    location: "US",
    managerId: "emp-058",
    workstreams: ["Checkout"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    tenure: 24,
  },
  {
    id: "emp-062",
    name: "Dennis Cox",
    title: "Engineering Manager",
    location: "Nearshore",
    managerId: "emp-058",
    workstreams: ["Checkout"],
    moduleOwnershipIds: [],
    primarySkill: "Fullstack",
    secondarySkills: [],
    tenure: 21,
  },
  {
    id: "emp-063",
    name: "Virginia Howard",
    title: "Engineering Manager",
    location: "US",
    managerId: "emp-059",
    workstreams: ["Fulfillment"],
    moduleOwnershipIds: ["mod-sub-011"],
    primarySkill: "Backend",
    secondarySkills: [],
    tenure: 23,
  },
  {
    id: "emp-064",
    name: "Jerry Ward",
    title: "Engineering Manager",
    location: "Nearshore",
    managerId: "emp-060",
    workstreams: ["Checkout"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - All",
    secondarySkills: [],
    tenure: 19,
  },

  // --- Principal Engineers (1) ---
  {
    id: "emp-065",
    name: "Catherine Torres",
    title: "Principal Engineer",
    location: "US",
    managerId: "emp-006",
    workstreams: ["Checkout", "Fulfillment"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: ["Architecture"],
    skillLevel: "Principal",
    tenure: 46,
  },

  // --- Staff Engineers (4) ---
  {
    id: "emp-066",
    name: "Arthur Peterson",
    title: "Staff Engineer",
    location: "US",
    managerId: "emp-061",
    workstreams: ["Checkout"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Staff",
    tenure: 30,
  },
  {
    id: "emp-067",
    name: "Julie Gray",
    title: "Staff Engineer",
    location: "Nearshore",
    managerId: "emp-062",
    workstreams: ["Checkout"],
    moduleOwnershipIds: [],
    primarySkill: "Fullstack",
    secondarySkills: [],
    skillLevel: "Staff",
    tenure: 27,
  },
  {
    id: "emp-068",
    name: "Carl Ramirez",
    title: "Staff Engineer",
    location: "US",
    managerId: "emp-063",
    workstreams: ["Fulfillment"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Staff",
    tenure: 29,
  },
  {
    id: "emp-069",
    name: "Diana James",
    title: "Staff Engineer",
    location: "US",
    managerId: "emp-064",
    workstreams: ["Checkout"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - All",
    secondarySkills: [],
    skillLevel: "Staff",
    tenure: 25,
  },

  // --- Senior Engineers (6) ---
  {
    id: "emp-070",
    name: "Willie Watson",
    title: "Senior Engineer",
    location: "Nearshore",
    managerId: "emp-061",
    workstreams: ["Checkout"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 21,
  },
  {
    id: "emp-071",
    name: "Teresa Brooks",
    title: "Senior Engineer",
    location: "Offshore",
    managerId: "emp-061",
    workstreams: ["Checkout"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 18,
  },
  {
    id: "emp-072",
    name: "Eugene Kelly",
    title: "Senior Engineer",
    location: "US",
    managerId: "emp-062",
    workstreams: ["Checkout"],
    moduleOwnershipIds: [],
    primarySkill: "Fullstack",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 20,
  },
  {
    id: "emp-073",
    name: "Brenda Sanders",
    title: "Senior Engineer",
    location: "Nearshore",
    managerId: "emp-063",
    workstreams: ["Fulfillment"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 19,
  },
  {
    id: "emp-074",
    name: "Albert Price",
    title: "Senior Engineer",
    location: "Offshore",
    managerId: "emp-063",
    workstreams: ["Fulfillment"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 17,
  },
  {
    id: "emp-075",
    name: "Annie Bennett",
    title: "Senior Engineer",
    location: "US",
    managerId: "emp-064",
    workstreams: ["Checkout"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - Web",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 16,
  },

  // --- Engineers (7) ---
  {
    id: "emp-076",
    name: "Sean Wood",
    title: "Engineer",
    location: "Nearshore",
    managerId: "emp-061",
    workstreams: ["Checkout"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 13,
  },
  {
    id: "emp-077",
    name: "Gloria Barnes",
    title: "Engineer",
    location: "Offshore",
    managerId: "emp-061",
    workstreams: ["Checkout"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 11,
  },
  {
    id: "emp-078",
    name: "Harold Ross",
    title: "Engineer",
    location: "US",
    managerId: "emp-062",
    workstreams: ["Checkout"],
    moduleOwnershipIds: [],
    primarySkill: "Fullstack",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 12,
  },
  {
    id: "emp-079",
    name: "Irene Henderson",
    title: "Engineer",
    location: "Nearshore",
    managerId: "emp-062",
    workstreams: ["Checkout"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - Web",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 10,
  },
  {
    id: "emp-080",
    name: "Philip Coleman",
    title: "Engineer",
    location: "Offshore",
    managerId: "emp-063",
    workstreams: ["Fulfillment"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 9,
  },
  {
    id: "emp-081",
    name: "Rose Jenkins",
    title: "Engineer",
    location: "US",
    managerId: "emp-063",
    workstreams: ["Fulfillment"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 14,
  },
  {
    id: "emp-082",
    name: "Howard Perry",
    title: "Engineer",
    location: "Nearshore",
    managerId: "emp-064",
    workstreams: ["Checkout"],
    moduleOwnershipIds: [],
    primarySkill: "Frontend - All",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 8,
  },

  // --- Associate Engineers (2) ---
  {
    id: "emp-083",
    name: "Phyllis Powell",
    title: "Associate Engineer",
    location: "Offshore",
    managerId: "emp-061",
    workstreams: ["Checkout"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Junior",
    tenure: 5,
  },
  {
    id: "emp-084",
    name: "Ralph Long",
    title: "Associate Engineer",
    location: "Offshore",
    managerId: "emp-063",
    workstreams: ["Fulfillment"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Junior",
    tenure: 4,
  },

  // ===== AI ENGINEERING MODULE (Director: Dr. James Chen) =====
  // --- Senior Engineering Managers (2) ---
  {
    id: "emp-085",
    name: "Shirley Patterson",
    title: "Senior Engineering Manager",
    location: "US",
    managerId: "emp-007",
    workstreams: ["Personalization"],
    moduleOwnershipIds: ["mod-sub-012"],
    primarySkill: "AI/ML",
    secondarySkills: [],
    tenure: 35,
  },
  {
    id: "emp-086",
    name: "Russell Hughes",
    title: "Senior Engineering Manager",
    location: "US",
    managerId: "emp-007",
    workstreams: ["Platform"],
    moduleOwnershipIds: ["mod-sub-013"],
    primarySkill: "Backend",
    secondarySkills: [],
    tenure: 32,
  },

  // --- Engineering Managers (3) ---
  {
    id: "emp-087",
    name: "Mildred Flores",
    title: "Engineering Manager",
    location: "US",
    managerId: "emp-085",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "AI/ML",
    secondarySkills: [],
    tenure: 26,
  },
  {
    id: "emp-088",
    name: "Lawrence Washington",
    title: "Engineering Manager",
    location: "Nearshore",
    managerId: "emp-085",
    workstreams: ["Search"],
    moduleOwnershipIds: ["mod-sub-014"],
    primarySkill: "Backend - Search",
    secondarySkills: [],
    tenure: 23,
  },
  {
    id: "emp-089",
    name: "Jane Butler",
    title: "Engineering Manager",
    location: "US",
    managerId: "emp-086",
    workstreams: ["Platform"],
    moduleOwnershipIds: ["mod-sub-015"],
    primarySkill: "Backend",
    secondarySkills: [],
    tenure: 24,
  },

  // --- Principal Engineers (2) ---
  {
    id: "emp-090",
    name: "Dr. Roy Simmons",
    title: "Principal Engineer",
    location: "US",
    managerId: "emp-007",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "AI/ML",
    secondarySkills: ["Architecture"],
    skillLevel: "Principal",
    tenure: 50,
  },
  {
    id: "emp-091",
    name: "Frances Foster",
    title: "Principal Engineer",
    location: "US",
    managerId: "emp-007",
    workstreams: ["Platform"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: ["Architecture"],
    skillLevel: "Principal",
    tenure: 44,
  },

  // --- Staff Engineers (3) ---
  {
    id: "emp-092",
    name: "Billy Gonzalez",
    title: "Staff Engineer",
    location: "US",
    managerId: "emp-087",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "AI/ML",
    secondarySkills: [],
    skillLevel: "Staff",
    tenure: 31,
  },
  {
    id: "emp-093",
    name: "Cheryl Bryant",
    title: "Staff Engineer",
    location: "Nearshore",
    managerId: "emp-088",
    workstreams: ["Search"],
    moduleOwnershipIds: [],
    primarySkill: "Backend - Search",
    secondarySkills: [],
    skillLevel: "Staff",
    tenure: 28,
  },
  {
    id: "emp-094",
    name: "Gerald Alexander",
    title: "Staff Engineer",
    location: "US",
    managerId: "emp-089",
    workstreams: ["Platform"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Staff",
    tenure: 26,
  },

  // --- Senior Engineers (5) ---
  {
    id: "emp-095",
    name: "Doris Russell",
    title: "Senior Engineer",
    location: "US",
    managerId: "emp-087",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "AI/ML",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 23,
  },
  {
    id: "emp-096",
    name: "Victor Griffin",
    title: "Senior Engineer",
    location: "Nearshore",
    managerId: "emp-087",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 20,
  },
  {
    id: "emp-097",
    name: "Evelyn Diaz",
    title: "Senior Engineer",
    location: "US",
    managerId: "emp-088",
    workstreams: ["Search"],
    moduleOwnershipIds: [],
    primarySkill: "Backend - Search",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 21,
  },
  {
    id: "emp-098",
    name: "Juan Hayes",
    title: "Senior Engineer",
    location: "Nearshore",
    managerId: "emp-088",
    workstreams: ["Search"],
    moduleOwnershipIds: [],
    primarySkill: "AI/ML",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 19,
  },
  {
    id: "emp-099",
    name: "Janice Myers",
    title: "Senior Engineer",
    location: "Offshore",
    managerId: "emp-089",
    workstreams: ["Platform"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Senior",
    tenure: 18,
  },

  // --- Engineers (6) ---
  {
    id: "emp-100",
    name: "Randy Ford",
    title: "Engineer",
    location: "Nearshore",
    managerId: "emp-087",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "AI/ML",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 15,
  },
  {
    id: "emp-101",
    name: "Marilyn Hamilton",
    title: "Engineer",
    location: "Offshore",
    managerId: "emp-087",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 13,
  },
  {
    id: "emp-102",
    name: "Vincent Graham",
    title: "Engineer",
    location: "US",
    managerId: "emp-088",
    workstreams: ["Search"],
    moduleOwnershipIds: [],
    primarySkill: "Backend - Search",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 14,
  },
  {
    id: "emp-103",
    name: "Joyce Sullivan",
    title: "Engineer",
    location: "Nearshore",
    managerId: "emp-088",
    workstreams: ["Search"],
    moduleOwnershipIds: [],
    primarySkill: "AI/ML",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 12,
  },
  {
    id: "emp-104",
    name: "Jack Wallace",
    title: "Engineer",
    location: "Offshore",
    managerId: "emp-089",
    workstreams: ["Platform"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 11,
  },
  {
    id: "emp-105",
    name: "Beverly Woods",
    title: "Engineer",
    location: "US",
    managerId: "emp-089",
    workstreams: ["Platform"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Mid",
    tenure: 10,
  },

  // --- Associate Engineers (3) ---
  {
    id: "emp-106",
    name: "Louis Cole",
    title: "Associate Engineer",
    location: "Offshore",
    managerId: "emp-087",
    workstreams: ["Personalization"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Junior",
    tenure: 6,
  },
  {
    id: "emp-107",
    name: "Katherine West",
    title: "Associate Engineer",
    location: "Offshore",
    managerId: "emp-088",
    workstreams: ["Search"],
    moduleOwnershipIds: [],
    primarySkill: "Backend - Search",
    secondarySkills: [],
    skillLevel: "Junior",
    tenure: 5,
  },
  {
    id: "emp-108",
    name: "Albert Reynolds",
    title: "Associate Engineer",
    location: "Nearshore",
    managerId: "emp-089",
    workstreams: ["Platform"],
    moduleOwnershipIds: [],
    primarySkill: "Backend",
    secondarySkills: [],
    skillLevel: "Junior",
    tenure: 4,
  },
];

// ============================================
// MODULES (4 main + 15 submodules = 19 total)
// ============================================

const modules: ModuleNode[] = [
  // ===== MAIN MODULES =====
  {
    id: "mod-001",
    name: "Traffic, Discovery & Growth",
    workstream: "Search",
    type: "Vertical",
    directorId: "emp-004",
    tags: ["Tier-0", "Revenue"],
    health: "Healthy",
    priority: "P0",
    description: "User acquisition, search, browse, and SEO",
  },
  {
    id: "mod-002",
    name: "Consideration",
    workstream: "Personalization",
    type: "Vertical",
    directorId: "emp-005",
    tags: ["Tier-0", "Customer-Experience"],
    health: "Healthy",
    priority: "P0",
    description: "Product discovery, comparison, and recommendations",
  },
  {
    id: "mod-003",
    name: "Purchase and Post-Purchase",
    workstream: "Checkout",
    type: "Vertical",
    directorId: "emp-006",
    tags: ["Tier-0", "Revenue"],
    health: "At Risk",
    priority: "P0",
    description: "Checkout, payment, order fulfillment, and post-purchase experience",
  },
  {
    id: "mod-004",
    name: "AI Engineering",
    workstream: "Personalization",
    type: "Horizontal",
    directorId: "emp-007",
    tags: ["Platform", "Innovation"],
    health: "Healthy",
    priority: "P1",
    description: "ML platform, personalization engine, and AI-powered features",
  },

  // ===== TRAFFIC, DISCOVERY & GROWTH SUBMODULES =====
  {
    id: "mod-sub-001",
    name: "Search",
    parentId: "mod-001",
    workstream: "Search",
    type: "Vertical",
    tags: ["Core"],
    health: "Healthy",
    priority: "P0",
  },
  {
    id: "mod-sub-002",
    name: "Browse & Discovery",
    parentId: "mod-001",
    workstream: "Browse",
    type: "Vertical",
    tags: ["Core"],
    health: "Healthy",
    priority: "P0",
  },
  {
    id: "mod-sub-003",
    name: "SEO",
    parentId: "mod-001",
    workstream: "SEO",
    type: "Vertical",
    tags: ["Growth"],
    health: "Healthy",
    priority: "P1",
  },
  {
    id: "mod-sub-004",
    name: "Growth",
    parentId: "mod-001",
    workstream: "Platform",
    type: "Horizontal",
    tags: ["Marketing"],
    health: "Healthy",
    priority: "P1",
  },

  // ===== CONSIDERATION SUBMODULES =====
  {
    id: "mod-sub-005",
    name: "Product Details",
    parentId: "mod-002",
    workstream: "Personalization",
    type: "Vertical",
    tags: ["Core"],
    health: "Healthy",
    priority: "P0",
  },
  {
    id: "mod-sub-006",
    name: "Comparison",
    parentId: "mod-002",
    workstream: "Personalization",
    type: "Vertical",
    tags: ["Feature"],
    health: "Healthy",
    priority: "P1",
  },
  {
    id: "mod-sub-007",
    name: "Recommendations",
    parentId: "mod-002",
    workstream: "Personalization",
    type: "Vertical",
    tags: ["AI"],
    health: "Healthy",
    priority: "P1",
  },

  // ===== PURCHASE AND POST-PURCHASE SUBMODULES =====
  {
    id: "mod-sub-008",
    name: "Checkout",
    parentId: "mod-003",
    workstream: "Checkout",
    type: "Vertical",
    tags: ["Tier-0", "Revenue"],
    health: "At Risk",
    priority: "P0",
  },
  {
    id: "mod-sub-009",
    name: "Payment",
    parentId: "mod-003",
    workstream: "Checkout",
    type: "Vertical",
    tags: ["Tier-0", "Revenue"],
    health: "Critical",
    priority: "P0",
  },
  {
    id: "mod-sub-010",
    name: "Order Fulfillment",
    parentId: "mod-003",
    workstream: "Fulfillment",
    type: "Vertical",
    tags: ["Core"],
    health: "Healthy",
    priority: "P0",
  },
  {
    id: "mod-sub-011",
    name: "Post-Purchase Experience",
    parentId: "mod-003",
    workstream: "Fulfillment",
    type: "Vertical",
    tags: ["Customer-Experience"],
    health: "Healthy",
    priority: "P1",
  },

  // ===== AI ENGINEERING SUBMODULES =====
  {
    id: "mod-sub-012",
    name: "Personalization",
    parentId: "mod-004",
    workstream: "Personalization",
    type: "Horizontal",
    tags: ["Platform"],
    health: "Healthy",
    priority: "P1",
  },
  {
    id: "mod-sub-013",
    name: "ML Platform",
    parentId: "mod-004",
    workstream: "Platform",
    type: "Horizontal",
    tags: ["Infrastructure"],
    health: "Healthy",
    priority: "P1",
  },
  {
    id: "mod-sub-014",
    name: "AI Search",
    parentId: "mod-004",
    workstream: "Search",
    type: "Horizontal",
    tags: ["Innovation"],
    health: "Healthy",
    priority: "P2",
  },
  {
    id: "mod-sub-015",
    name: "Recommendations Engine",
    parentId: "mod-004",
    workstream: "Personalization",
    type: "Horizontal",
    tags: ["Platform"],
    health: "Healthy",
    priority: "P1",
  },
];

// ============================================
// OWNERSHIP
// ============================================

const ownership: Ownership[] = [
  // Director ownership (already specified in moduleOwnershipIds)
  { moduleId: "mod-001", ownerId: "emp-004", ownershipType: "Primary" },
  { moduleId: "mod-002", ownerId: "emp-005", ownershipType: "Primary" },
  { moduleId: "mod-003", ownerId: "emp-006", ownershipType: "Primary" },
  { moduleId: "mod-004", ownerId: "emp-007", ownershipType: "Primary" },
  
  // Submodule ownership by SEMs
  { moduleId: "mod-sub-001", ownerId: "emp-008", ownershipType: "Primary" },
  { moduleId: "mod-sub-002", ownerId: "emp-009", ownershipType: "Primary" },
  { moduleId: "mod-sub-003", ownerId: "emp-011", ownershipType: "Primary" },
  { moduleId: "mod-sub-004", ownerId: "emp-012", ownershipType: "Primary" },
  { moduleId: "mod-sub-005", ownerId: "emp-034", ownershipType: "Primary" },
  { moduleId: "mod-sub-006", ownerId: "emp-035", ownershipType: "Primary" },
  { moduleId: "mod-sub-007", ownerId: "emp-038", ownershipType: "Primary" },
  { moduleId: "mod-sub-008", ownerId: "emp-058", ownershipType: "Primary" },
  { moduleId: "mod-sub-009", ownerId: "emp-060", ownershipType: "Primary" },
  { moduleId: "mod-sub-010", ownerId: "emp-059", ownershipType: "Primary" },
  { moduleId: "mod-sub-011", ownerId: "emp-063", ownershipType: "Primary" },
  { moduleId: "mod-sub-012", ownerId: "emp-085", ownershipType: "Primary" },
  { moduleId: "mod-sub-013", ownerId: "emp-086", ownershipType: "Primary" },
  { moduleId: "mod-sub-014", ownerId: "emp-088", ownershipType: "Primary" },
  { moduleId: "mod-sub-015", ownerId: "emp-089", ownershipType: "Primary" },
];

// ============================================
// EXPORT
// ============================================

export const mockOrgState: ShiptOrgState = {
  employees,
  modules,
  ownership,
};